### ISSUE TITLE
Can't Open/Run application anymore

### ISSUE THREAD

**Issue by iisbetoq** [jpage4500/AndroidDeviceManager#5]
First of all, I want to thank you for the extraordinary application, I really liked it the first time I used it.

Previously I could run the application smoothly without any problems, but for the past few days I haven't been able to open/run the application, I tried updating the JRE but it still doesn't work, running via desktop (double click) or terminal is the same.

The following message displays when run via the terminal

java -jar AndroidDeviceManager.jar
06/09 01:05:56: [1]: D: MainApplication: MainApplication: APP START: 24.05.30.2018, java:22.0.1+8-16, os:Linux
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 5 >= 5
	at java.base/java.util.Vector.elementAt(Vector.java:466)
	at java.desktop/javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:298)
	at com.jpage4500.devicemanager.ui.DeviceScreen.setupTable(DeviceScreen.java:227)
	at com.jpage4500.devicemanager.ui.DeviceScreen.initalizeUi(DeviceScreen.java:126)
	at com.jpage4500.devicemanager.ui.DeviceScreen.<init>(DeviceScreen.java:63)
	at com.jpage4500.devicemanager.MainApplication.initializeUI(MainApplication.java:87)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

my OS is Linux with java -version
java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

I don't know where the problem because other Java applications can run normally
2024.05.30 - i can run the app before but can't run anymore
2024.05.24 - i can run the app until now

Regards

**Comment by jpage4500** [comment]
Hi,

I probably fixed this already in the branch I've been working on. I just merged my branch into develop if you'd like to try that. I've done a lot of work on many different areas so there's still lots that will be changing -- but once it slows down a bit I'll add a new release as well

thanks!
